# Generated by Django 4.2.2 on 2023-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
