# Generated by Django 4.2.2 on 2023-06-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description2',
        ),
    ]
