# Generated by Django 4.2.2 on 2023-06-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_group',
            field=models.PositiveIntegerField(choices=[(5, 'kleine Gruppe'), (10, 'mittelgrosse Gruppe'), (20, 'sehr große Gruppe'), (0, 'ohne Begrenzung')], default=0),
            preserve_default=False,
        ),
    ]
