# Generated by Django 4.2.2 on 2023-06-14 10:23

import django.core.validators
from django.db import migrations, models
import events.validators


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_category_options_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(validators=[events.validators.date_in_past]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[events.validators.BadWordFilter(['evil', 'doofi'])]),
        ),
    ]
